--- # Poggit-CI Manifest. Open the CI at https://poggit.pmmp.io/ci/nhanaz-pm-pl/NoCraftItem
build-by-default: true
branches:
- master
projects:
  NoCraftItem:
    path: ""
    libs:
      - src: NhanAZ/libBedrock/libBedrock
        version: 0.0.8
...
